### ISSUE TITLE
Web interface doesn't work when running as non root user

### ISSUE THREAD

**Issue by romcheck** [titpetric/netdata#39] opened 2017-01-27 17:06 UTC
I start with env variable -u netdata. So command looks like:

` netdata -u root -u netdata`

Some redundancy does not bother me.

But web interface shows me:

`Access to file is not permitted: &#x2F;usr&#x2F;share&#x2F;netdata&#x2F;web&#x2F;`

In netdata logs I found this:

`netdata    | 2017-01-27 18:53:51: netdata: ERROR: 1: File '/usr/share/netdata/web/' is owned by user 0 (expected user 999). Access Denied.`

Netdata expects owner of web dir is to be netdata user (userid 999).

I think, solution is to build image as netdata user.

**Comment by ghost** [comment] 2017-01-27 21:52
I get the same error when starting with 

`docker run --name netdata -d --cap-add SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro titpetric/netdata`

and accessing with an nginx frontend.

**Comment by titpetric** [comment] 2017-02-01 14:56
I have tested the latest release with:

`docker run -e NETDATA_PORT=8081 -p 8081:8081 --name netdata -d --cap-add SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro titpetric/netdata`

and opening the resulting page in a browser. There are no apparent issues.

Please provide more information:

1. steps to reproduce (full docker run command),
2. observed issue, description expected behaviour

**Comment by romcheck** [comment] 2017-02-01 16:02
1. Try to test with:

` docker run -e NETDATA_ARGS="-u netdata" -p 19999:19999 -d --cap-add SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro titpetric/netdata`

2. curl localhost:19999

> Access to file is not permitted: &#x2F;usr&#x2F;share&#x2F;netdata&#x2F;web&#x2F

Expected behavior is to find netdata web interface when I go to http://localhost:19999.

**Comment by ghost** [comment] 2017-02-01 19:28
I had this same error because of a wrongly configured nginx container. Once I more or less followed the [wiki](https://github.com/firehol/netdata/wiki/Running-behind-nginx), it worked.

**Comment by romcheck** [comment] 2017-02-01 19:48
**@uncertaintyiseverywhere**, how did you manage to find nginx container in this simple `docker run titpetric/netdata` command?

**Comment by ghost** [comment] 2017-02-01 20:19
@romcheck: Oohh, this is a confusion. I never meant to post that first comment, since I managed to get it working. I just now realised that I posted it by accident and that titpetric responded to me.

Sorry for that confusion. Might still help someone actually using nginx in a container though.

**Comment by titpetric** [comment] 2017-02-02 05:23
@romcheck is there some specific reason you want to run with -u netdata? Security?

**Comment by romcheck** [comment] 2017-02-03 09:25
@titpetric yes, this is just the reason now.

**Comment by JOduMonT** [comment] 2017-05-26 07:45
Hi @titpetric 

I have the same kind of issue : **Access to file is not permitted: /usr/share/netdata/web/index.html**

I try 
NETDATA_ARGS="-u netdata and NETDATA_ARGS="-u root just for fun but each time I receive a weird mix of permission in 

```
root@732e4158e126:/usr/share/netdata/web# ls -lah
total 868K
drwxrwxr-x 14 root    root     104 May 26 07:35 .
drwxrwxr-x  4 root    root      17 May 26 07:35 ..
drwxrwxr-x  4 root    root      17 May 26 07:35 .well-known
drwxrwxr-x  2 root    root       6 May 24 20:48 css
-rw-rw-r--  1 netdata netdata  17K May 24 20:48 dashboard.css
-rw-rw-r--  1 netdata netdata  22K May 24 20:48 dashboard.html
-rw-rw-r--  1 netdata netdata 288K May 24 20:48 dashboard.js
-rw-rw-r--  1 netdata netdata  17K May 24 20:48 dashboard.slate.css
-rw-rw-r--  1 netdata netdata  54K May 24 20:48 dashboard_info.js
-rw-rw-r--  1 netdata netdata 1.8K May 24 20:48 dashboard_info_custom_example.js
-rw-rw-r--  1 netdata netdata 2.0K May 24 20:48 demo.html
-rw-rw-r--  1 netdata netdata 6.7K May 24 20:48 demo2.html
-rw-rw-r--  1 netdata netdata  62K May 24 20:48 demosites.html
-rw-rw-r--  1 netdata netdata  47K May 24 20:48 demosites2.html
-rw-rw-r--  1 netdata netdata  56K May 24 20:48 favicon.ico
drwxrwxr-x  2 root    root       6 May 24 20:48 fonts
-rw-rw-r--  1 netdata netdata 8.0K May 24 20:48 goto-host-from-alarm.html
drwxrwxr-x  2 root    root       6 May 24 20:48 images
-rw-rw-r--  1 netdata netdata 174K May 24 20:48 index.html
-rw-rw-r--  1 netdata netdata 9.8K May 24 20:48 infographic.html
drwxrwxr-x  2 root    root       6 May 24 20:48 lib
-rw-rw-r--  1 netdata netdata  31K May 24 20:48 netdata-swagger.json
-rw-rw-r--  1 netdata netdata  20K May 24 20:48 netdata-swagger.yaml
drwxrwxr-x  2 root    root       6 May 24 20:48 old
-rw-rw-r--  1 netdata netdata 7.6K May 24 20:48 registry.html
-rw-rw-r--  1 netdata netdata  119 May 24 20:48 robots.txt
-rw-rw-r--  1 netdata netdata  283 May 24 20:48 sitemap.xml
-rw-rw-r--  1 netdata netdata  12K May 24 20:48 tv.html
-rw-rw-r--  1 netdata netdata    0 May 24 20:48 version.txt
root@732e4158e126:/usr/share/netdata/web# 
```

What worst is I have one with the exact same config and it work since 6weeks

but in this one
everything is owned by root

```
root@592d6dffeaa4:/# ls -lha /usr/share/netdata/web/
total 988K
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 .
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 ..
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 .well-known
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 css
-rw-rw-r--. 1 root root  17K Apr  6 22:28 dashboard.css
-rw-rw-r--. 1 root root  22K Apr  6 22:28 dashboard.html
-rw-rw-r--. 1 root root 277K Apr  6 22:28 dashboard.js
-rw-rw-r--. 1 root root  17K Apr  6 22:28 dashboard.slate.css
-rw-rw-r--. 1 root root  54K Apr  6 22:28 dashboard_info.js
-rw-rw-r--. 1 root root 1.8K Apr  6 22:28 dashboard_info_custom_example.js
-rw-rw-r--. 1 root root 2.0K Apr  6 22:28 demo.html
-rw-rw-r--. 1 root root 6.7K Apr  6 22:28 demo2.html
-rw-rw-r--. 1 root root  60K Apr  6 22:28 demosites.html
-rw-rw-r--. 1 root root  47K Apr  6 22:28 demosites2.html
-rw-rw-r--. 1 root root  56K Apr  6 22:28 favicon.ico
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 fonts
-rw-rw-r--. 1 root root 8.0K Apr  6 22:28 goto-host-from-alarm.html
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 images
-rw-rw-r--. 1 root root 173K Apr  6 22:28 index.html
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 lib
-rw-rw-r--. 1 root root  31K Apr  6 22:28 netdata-swagger.json
-rw-rw-r--. 1 root root  20K Apr  6 22:28 netdata-swagger.yaml
drwxrwxr-x. 1 root root 4.0K Apr  6 22:28 old
-rw-rw-r--. 1 root root 7.6K Apr  6 22:28 registry.html
-rw-rw-r--. 1 root root  119 Apr  6 22:28 robots.txt
-rw-rw-r--. 1 root root  283 Apr  6 22:28 sitemap.xml
-rw-rw-r--. 1 root root  12K Apr  6 22:28 tv.html
-rw-rw-r--. 1 root root    0 Apr 12 06:13 version.txt
root@592d6dffeaa4:/# 
```

Those two hosts are different
the working one is CoreOS with Docker 1.12.6 and using Overlay
the non working one is Ubuntu 16.04LTS with Docker 17.05.0-ce and using aufs


I just replace
titpetric/netdata by firehol/netdata
and it work perfectly
even with -e NETDATA_ARGS="-u netdata"

> root@701e350f1de5:/usr/share/netdata/web# ls -lah
> total 888K
> drwxrwxr-x 8 netdata netdata 4.0K May 24 20:42 .
> drwxrwxr-x 3 root    root      17 May 24 20:42 ..
> drwxrwxr-x 3 netdata netdata   17 May 24 20:42 .well-known
> drwxrwxr-x 2 netdata netdata  223 May 24 20:42 css
> -rw-rw-r-- 1 netdata netdata  17K May 24 20:42 dashboard.css
> -rw-rw-r-- 1 netdata netdata  22K May 24 20:42 dashboard.html
> -rw-rw-r-- 1 netdata netdata 288K May 24 20:42 dashboard.js
> -rw-rw-r-- 1 netdata netdata  17K May 24 20:42 dashboard.slate.css
> -rw-rw-r-- 1 netdata netdata  54K May 24 20:42 dashboard_info.js
> -rw-rw-r-- 1 netdata netdata 1.8K May 24 20:42 dashboard_info_custom_example.js
> -rw-rw-r-- 1 netdata netdata 2.0K May 24 20:42 demo.html
> -rw-rw-r-- 1 netdata netdata 6.7K May 24 20:42 demo2.html
> -rw-rw-r-- 1 netdata netdata  62K May 24 20:42 demosites.html
> -rw-rw-r-- 1 netdata netdata  47K May 24 20:42 demosites2.html
> -rw-rw-r-- 1 netdata netdata  56K May 24 20:42 favicon.ico
> drwxrwxr-x 2 netdata netdata 4.0K May 24 20:42 fonts
> -rw-rw-r-- 1 netdata netdata 8.0K May 24 20:42 goto-host-from-alarm.html
> drwxrwxr-x 2 netdata netdata 4.0K May 24 20:42 images
> -rw-rw-r-- 1 netdata netdata 174K May 24 20:42 index.html
> -rw-rw-r-- 1 netdata netdata 9.8K May 24 20:42 infographic.html
> drwxrwxr-x 2 netdata netdata 4.0K May 24 20:42 lib
> -rw-rw-r-- 1 netdata netdata  31K May 24 20:42 netdata-swagger.json
> -rw-rw-r-- 1 netdata netdata  20K May 24 20:42 netdata-swagger.yaml
> drwxrwxr-x 2 netdata netdata   98 May 24 20:42 old
> -rw-rw-r-- 1 netdata netdata 7.6K May 24 20:42 registry.html
> -rw-rw-r-- 1 netdata netdata  119 May 24 20:42 robots.txt
> -rw-rw-r-- 1 netdata netdata  283 May 24 20:42 sitemap.xml
> -rw-rw-r-- 1 netdata netdata  12K May 24 20:42 tv.html
> -rw-rw-r-- 1 netdata netdata   41 May 24 20:42 version.txt

**Comment by titpetric** [comment] 2017-05-26 13:45
Hmm, thanks for the additional info. Must be something in the Dockerfile between the two versions, I'll take a look to see what's going on.

**Comment by titpetric** [comment] 2017-06-27 09:23
If someone has time to look at and fix the issue with the permissions with a slight howto or pull request, contributions are welcome.

**Comment by titpetric** [comment] 2017-10-09 08:37
I think I'm going to close this, not because it's implemented, but because it most likely never will be. If anybody wants to do it and submit a PR down the line, I'm willing to merge it. So far, there's no interest showing in comments or subscribers to this task so I'm considering it abandoned & closing.

**Closed as completed by titpetric** 2017-10-09 08:37 UTC
Labels: help wanted
